/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    domains: [
      'cdn.snapi.dev',
      'stockanalysis.com',
      'static.seekingalpha.com',
      'media.reuters.com',
      'images.wsj.net',
      's3-symbol-logo.tradingview.com',
      'assets.bwbx.io',
      'www.barrons.com',
      'www.marketwatch.com',
      'www.foxbusiness.com',
      'www.fxempire.com',
      'www.investing.com',
      'www.cnbc.com',
      'www.fool.com',
      'www.investopedia.com',
      'www.nasdaq.com',
      'www.zacks.com',
      'www.yahoo.com',
      'www.benzinga.com',
      'www.businessinsider.com',
      'www.forbes.com',
      'www.ft.com',
      'www.bloomberg.com',
      'www.seekingalpha.com',
      'www.tradingview.com',
      'www.prnewswire.com',
      'www.globenewswire.com',
      'www.marketpulse.com',
      'www.thestreet.com',
      'www.investingcube.com',
      'www.economist.com',
      'www.moneycontrol.com',
      'www.livemint.com',
      'www.businesstoday.in',
      'www.financialexpress.com',
      'www.thehindubusinessline.com',
      'www.thehindu.com',
      'www.reuters.com',
      'www.bbc.com',
      'www.nytimes.com',
      'www.wsj.com',
      'a57.foxnews.com',
      'responsive.fxempire.com',
      'nypost.com',
      'image.cnbcfm.com',
      'cdn.benzinga.com',
    ],
  },
  webpack: (config, { isServer }) => {
    config.cache = false;
    return config;
  },
};

module.exports = nextConfig;
