name: Market Movers Script Cron

on:
  schedule:
    # Runs at 03:00 UTC (after momentum screener completes at ~02:15)
    - cron: "0 3 * * *"

jobs:
  run-market-movers-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run market movers script
        env:
          SUPABASE_URL: https://rmiqzkojnxbugnszcpsy.supabase.co
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaXF6a29qbnhidWduc3pjcHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjEwMDcsImV4cCI6MjA2MjAzNzAwN30.Y4lFBFYs3n3jw-IcnhVk44i-s0HgvuQtqzUmGTzLvrI
        run: |
          npm ci
          npx tsx scripts/refresh-market-movers-db.ts
