name: Momentum Screener Script Cron

on:
  # Disabled - Using API endpoint cron instead for better reliability
  # schedule:
  #   - cron: "0 4 * * *"
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  run-screener-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run momentum screener script
        run: |
          npm ci
          node scripts/refresh-momentum-screener.js
